name: splitmask
channels:
  - conda-forge
dependencies:
  - python>3.7
  - jupyter
  - jupyterlab
  - pip
  - ipympl
  - pip:
    - tqdm
    - git+https://github.com/guiwitz/splitmask.git@master#egg=splitmask
